### ISSUE TITLE
Dead link in readme.md

### ISSUE THREAD

**Issue by chtof** [punker76/code-samples#12]
In readme.md, we can read : 
MahAppsMetroThemesSample MahApps.Metro ThemeManager example explained in this [blog post](http://jkarger.de/archive/2014/11/27/mahapps-metro-themes/).
But the link to http://jkarger.de/archive/2014/11/27/mahapps-metro-themes/ seems to be dead.
Could you correct the link or the readme.md file?

Thank you.

**Comment by chtof** [comment]
The correct link is: https://jkarger.de/2014/11/27/mahapps-metro-themes/

**Comment by punker76** [comment]
@chtof this has now been fixed. Thx for reporting this.
