### ISSUE TITLE
Flyout appears transparent

### ISSUE THREAD

**Issue by evilbaschdi** [punker76/code-samples#2]
I've played around with your ThemeManagerHelper from
https://github.com/punker76/code-samples/blob/master/MahAppsMetroThemesSample/MahAppsMetroThemesSample/ThemeManagerHelper.cs

This is working very well except my flyouts appearing transparent choosing one of the accents created through your class.
I already took a look into the other styles code but not find any differences that will fix this problem.

**Comment by evilbaschdi** [comment]
ok, it was my fault. I introduced my HighlightColor with transparency.

**Comment by punker76** [comment]
@evilbaschdi ok, but I'll update the source for the latest MahApps version and add a Flyout for testing
